{
 "title": "HAProxy",
 "description": "HAProxy Servers metrics",
 "time": { "from": "now-30h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(haproxy_up, instance)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_bytes_in_total{instance=~\"$instance\"}, frontend)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_server_bytes_in_total{instance=\"$instance\"}, backend)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_bytes_in_total{instance=~\"$instance\"}, server)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_server_http_responses_total{instance=~\"$instance\", server=~\"$server\"}, code)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Basic Backend status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backends Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(haproxy_backend_up{instance=~\"$instance\"} == 1)",
     "legendFormat": "Backends Up"
    },
    {
     "expr": "count(haproxy_backend_up{instance=~\"$instance\"} == 0)",
     "legendFormat": "Backends Down"
    }
   ]
  },
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HTTP responses by server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_http_responses_total{instance=\"$instance\",backend=~\"$backend\",code=~\"$code\"}[5m])",
     "legendFormat": "{{ server }}/{{ code }}"
    }
   ]
  },
  {
   "title": "Total responses by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\",instance=~\"$instance\"}[5m])) by (code)",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\",instance=~\"$instance\"}[5m])) by (code)",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Total number of connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{frontend=~\"$frontend\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{backend=~\"$backend\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Backend errors"
    }
   ]
  },
  {
   "title": "Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "OUT Back"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Front - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",instance=~\"$instance\"}[5m])",
     "legendFormat": "IN-{{ frontend }}"
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",instance=~\"$instance\"}[5m])",
     "legendFormat": "OUT-{{ frontend }}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{frontend=~\"$frontend\",instance=~\"$instance\"})",
     "legendFormat": "Frontend current sessions"
    },
    {
     "expr": "sum(haproxy_frontend_current_session_rate{frontend=~\"$frontend\",instance=~\"$instance\"})",
     "legendFormat": "Frontend current session rate"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{backend=~\"$backend\",instance=~\"$instance\"})",
     "legendFormat": "Backend current sessions"
    },
    {
     "expr": "sum(haproxy_backend_current_session_rate{backend=~\"$backend\",instance=~\"$instance\"})",
     "legendFormat": "Backend current session rate"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Front - Total number of connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_connections_total{frontend=~\"$frontend\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Front - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{frontend=~\"$frontend\",instance=~\"$instance\"}",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Front - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_session_rate{frontend=~\"$frontend\",instance=~\"$instance\"}",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of active sessions and limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_sessions{frontend=~\"$frontend\",instance=~\"$instance\"}",
     "legendFormat": "{{ frontend }}"
    },
    {
     "expr": "haproxy_frontend_limit_sessions{frontend=~\"$frontend\",instance=~\"$instance\"}",
     "legendFormat": "{{ frontend }} limit"
    }
   ]
  },
  {
   "title": "Front - Maximum number of sessions rate per second and limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_session_rate{frontend=~\"$frontend\",instance=~\"$instance\"}",
     "legendFormat": "{{ frontend }}"
    },
    {
     "expr": "haproxy_frontend_limit_session_rate{frontend=~\"$frontend\",instance=~\"$instance\"}",
     "legendFormat": "{{ frontend }} limit"
    }
   ]
  },
  { "title": "By Server Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Server - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_bytes_in_total{server=~\"$server\",instance=~\"$instance\"}[5m])",
     "legendFormat": "IN-{{ backend }} / {{ server }}"
    },
    {
     "expr": "rate(haproxy_server_bytes_out_total{server=~\"$server\",instance=~\"$instance\"}[5m])",
     "legendFormat": "OUT-{{ backend }} / {{ server }}"
    }
   ]
  },
  { "title": "By Server Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Server Connections Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_connection_errors_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }
  },
  {
   "title": "Server - Total of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{code=~\"$code\",instance=~\"$instance\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  { "title": "By Server Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Server - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{instance=~\"$instance\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_session_rate{instance=~\"$instance\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  }
 ]
}