{
 "title": "Memcached",
 "description": "Memcached Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(memcached_up,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "memcached_up{instance=\"$instance\"}",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "memcached_uptime_seconds{instance=\"$instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Commands Pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (command) (memcached_commands_total{instance=\"$instance\"})",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Get Hit/Miss Pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (status) (memcached_commands_total{instance=\"$instance\",status=~\"hit|miss\",command=\"get\"})",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Current Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_current_connections{instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "memcached_max_connections{instance=\"$instance\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Current Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_current_items{instance=\"$instance\"}",
     "legendFormat": "items"
    }
   ]
  },
  {
   "title": "Current Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "memcached_current_bytes{instance=\"$instance\"}",
     "legendFormat": "bytes"
    },
    {
     "expr": "memcached_limit_bytes{instance=\"$instance\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network Read/Written Bytes Ratio",
   "type": "graph",
   "description": "Ratio of bytes written (sent) and read by this server to network.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_read_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(memcached_written_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "written"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Connections Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_connections_total{instance=\"$instance\"}[5m])",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Connections Yielded",
   "type": "graph",
   "description": "Total number of connections yielded running due to hitting the memcached -R limit. A limit to the number of sequential requests the server will process from an individual client connection.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_connections_yielded_total{instance=\"$instance\"}[5m])",
     "legendFormat": "connections yielded"
    }
   ]
  },
  {
   "title": "Connections Listener Disabled",
   "type": "graph",
   "description": "Number of times that memcached has hit its connections limit and disabled its listener",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_connections_listener_disabled_total{instance=\"$instance\"}[5m])",
     "legendFormat": "counter rate"
    }
   ]
  },
  { "title": "Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Items Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_items_total{instance=\"$instance\"}[5m])",
     "legendFormat": "items"
    }
   ]
  },
  {
   "title": "Items Evicted Rate",
   "type": "graph",
   "description": "Valid items removed from cache to free memory for new items",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_items_evicted_total{instance=\"$instance\"}[5m])",
     "legendFormat": "items"
    }
   ]
  },
  {
   "title": "Items Reclaimed Rate",
   "type": "graph",
   "description": "Number of times an entry was stored using memory from an expired entry",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_items_reclaimed_total{instance=\"$instance\"}[5m])",
     "legendFormat": "items"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Command Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (rate(memcached_commands_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Command Status Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(memcached_commands_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Hit Ratio %",
   "type": "graph",
   "description": "Hit commands / All commands",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (memcached_commands_total{instance=\"$instance\",status=\"hit\"}) / sum by (command) (memcached_commands_total{instance=\"$instance\"})",
     "legendFormat": "{{ command }} ratio"
    }
   ]
  },
  {
   "title": "Miss Ratio %",
   "type": "graph",
   "description": "Missed commands / All commands",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (memcached_commands_total{instance=\"$instance\",status=\"miss\"}) / sum by (command) (memcached_commands_total{instance=\"$instance\"})",
     "legendFormat": "{{ command }} ratio"
    }
   ]
  },
  {
   "title": "Get Hit/Miss Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_commands_total{instance=\"$instance\",status=\"hit\",command=\"get\"}[5m])",
     "legendFormat": "Hit"
    },
    {
     "expr": "rate(memcached_commands_total{instance=\"$instance\",status=\"miss\",command=\"get\"}[5m])",
     "legendFormat": "Miss"
    }
   ]
  }
 ]
}